---

- name: Instalaci贸n de slapd mediante m贸dulo shell
  hosts: srv1

  tasks:
    - name: Configurar preguntas de instalaci贸n
      ansible.builtin.shell:
        cmd: debconf-set-selections
        stdin: |
          slapd shared/organization string esei.uvigo.es
          slapd slapd/domain string esei.uvigo.es
          slapd slapd/dump_database select when needed
          slapd slapd/dump_database_destdir string /var/backups/slapd-VERSION
          slapd slapd/internal/adminpw password abc123.
          slapd slapd/internal/generated_adminpw password abc123. 
          slapd slapd/invalid_config boolean true
          slapd slapd/move_old_database boolean true
          slapd slapd/no_configuration boolean false
          slapd slapd/password1 password 
          slapd slapd/password2 password 
          slapd slapd/password_mismatch note 
          slapd slapd/postinst_error note 
          slapd slapd/purge_database boolean false
          slapd slapd/upgrade_slapcat_failure error

    - name: Instalaci贸n del slapd
      ansible.builtin.apt:
        name: slapd
        state: present
        update_cache: yes